### ISSUE TITLE
Priorization of function codes

### ISSUE THREAD

**Issue by fkromer** [deviator/modbus#6]
What function codes of the [application protocol specification](http://www.modbus.org/docs/Modbus_Application_Protocol_V1_1b3.pdf) are on your todo list? And how do you prioritize them? (I integrated a C Modbus client stack into an application some years ago and could probably help out a bit.)

**Comment by deviator** [comment]
We use in our devices only functions what are implemented (1,2,3,4,5,6,16) and 42 as specific service function (in specification it's reserved). If you need other, you can list them here and I implement those later.
Or welcome to pull requests =)

**Comment by fkromer** [comment]
I am not using Modbus right now and I have no immediate need for specific functions. I just wanted to contribute to some industry related D package 😉.
